#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Apr 29, 2023 05:15:47 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #d9d9d9
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background azure4 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 630x420+954+511
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "TNotebook Style Demo"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook "$top.tNo47" \
        -width 462 -height 266 -takefocus {} 
    vTcl:DefineAlias "$top.tNo47" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    frame "$top.tNo47.t0" \
        -background coral2 -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t0 \
        -padding 0 -sticky nsew -state normal -text "Page 1" -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo47.t0
    button "$site_4_0.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text "Button" 
    vTcl:DefineAlias "$site_4_0.but47" "Button4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.but47 \
        -in $site_4_0 -x 200 -y 90 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t1" \
        -background navajowhite3 -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t1 \
        -padding 0 -sticky nsew -state normal -text "Page 2" -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo47.t1
    button "$site_4_1.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text "Button" 
    vTcl:DefineAlias "$site_4_1.but50" "Button3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_1.but50 \
        -in $site_4_1 -x 180 -y 90 -width 93 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t2" \
        -background seagreen2 -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t2 \
        -padding 0 -sticky nsew -state normal -text "Page 3" -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo47.t2
    button "$site_4_2.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text "Button" 
    vTcl:DefineAlias "$site_4_2.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_2.but49 \
        -in $site_4_2 -x 180 -y 90 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t3" \
        -background cadetblue -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t3" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t3 \
        -padding 0 -sticky nsew -state normal -text "Page 4" -image {} \
        -compound left -underline -1 
    set site_4_3  $top.tNo47.t3
    button "$site_4_3.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text "Button" 
    vTcl:DefineAlias "$site_4_3.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_3.but48 \
        -in $site_4_3 -x 160 -y 80 -width 113 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo47 \
        -in $top -x 80 -y 60 -width 462 -relwidth 0 -height 266 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

